// 26/11/23
class Demo9{
	public static void main(String[] args){
		int[] a = {10, 20, 30};
		try{
			System.out.println(10/2);
			System.out.println(a[20]);
		}
		catch(Exception e){
			System.out.println("Inside catch block Exception");
		}
	}
}